exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3.11
    stages: [commit]

- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    language_version: python3.11
    stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    language_version: python3.11
    stages: [commit]


- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    stages: [push]
    pass_filenames: false
    always_run: true