[tool.poetry]
name = "stl-dsa"
version = "0.1.0"
description = "A Django + Wagtail based website for the St Louis Chapter of DSA"
authors = ["Tyler Schlichenmeyer <tyler.schlichenmeyer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.0"
Django = "^4.1.4"
django-allauth = "^0.51.0"
django-extensions = "^3.1.5"
django-crispy-forms = "^1.14.0"
django-environ = "^0.9.0"
whitenoise = "^6.2.0"
django-rest-framework = "^0.1.0"
wagtail = "^4.0.2"
argon2-cffi = "^20.1.0"
wagtailmenus = "^3.1.2"
django-anymail = "^8.1"
gunicorn = "^20.0.4"
django-redis = "^4.12.1"
django-scheduler = "^0.9.3"
wagtailfontawesome = "^1.2.1"
requests = "^2.26.0"
python-dateutil = "^2.8.2"
django-cache-url = "^3.2.3"
validators = "^0.18.2"
django-compressor = "^2.4.1"
vcrpy = "^4.1.1"
psycopg2 = "^2.9.3"
black = "^22.3.0"
django-phonenumber-field = "^6.3.0"
phonenumbers = "^8.12.51"
django-storages = "^1.12.3"
python-decouple = "^3.6"
boto3 = "^1.24.23"
django-render-block = "^0.9.1"
polling2 = "^0.5.0"
raygun4py = "^4.3.2"
poetry-core = "^1.3.2"
mypy = "^0.991"
l18n = "^2021.3"

[tool.poetry.dev-dependencies]
psycopg2-binary = "^2.8.5"
pytest-django = "^4.4.0"
factory-boy = "^3.2.0"
django-seed = "^0.2.2"
Faker = "^8.10.1"
pytest = "^6.2.4"
flake8 = "^3.9.2"
django-debug-toolbar = "^3.5.0"
pytest-drf = "^1.1.2"
pre-commit = "^2.14.0"
pytest-cov = "^2.12.1"
django-coverage-plugin = "^2.0.0"
pytest-socket = "^0.4.1"
model-bakery = "^1.3.2"
responses = "0.16.0"
stringcase = "^1.2.0"
pytest-mock = "^3.7.0"
pytest-vcr = "^1.0.2"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --disable-socket --no-migrations"
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]

[tool.flake8]
max-line-length = 88
select = "C,E,F,W,B,B950"
extend-ignore = "E203, E501"

[tool.black]
extend_exclude = '^.*\b(migrations)\b.*$'


[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
