[tool.poetry]
name = "stl-dsa"
version = "0.1.0"
description = "A Django + Wagtail based website for the St Louis Chapter of DSA"
authors = ["Tyler Schlichenmeyer <tyler.schlichenmeyer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.0"
Django = "^4.1.4"
django-allauth = "^0.51.0"
django-crispy-forms = "^1.14.0"
django-environ = "^0.9.0"
whitenoise = "^6.2.0"
django-rest-framework = "^0.1.0"
wagtail = "^4.0.2"
argon2-cffi = "^20.1.0"
wagtailmenus = "^3.1.2"
django-anymail = "^8.1"
gunicorn = "^20.0.4"
django-redis = "^4.12.1"
wagtailfontawesome = "^1.2.1"
requests = "^2.28.1"
python-dateutil = "^2.8.2"
django-cache-url = "^3.2.3"
validators = "^0.18.2"
django-compressor = "^2.4.1"
psycopg2 = "^2.9.3"
black = "^22.3.0"
django-phonenumber-field = "^6.3.0"
phonenumbers = "^8.12.51"
django-storages = "^1.12.3"
boto3 = "^1.24.23"
django-render-block = "^0.9.1"
polling2 = "^0.5.0"
raygun4py = "^4.3.2"
poetry-core = "^1.3.2"
mypy = "^0.991"
l18n = "^2021.3"
types-requests = "^2.28.11.5"
django-sass = "^1.1.0"
pylint = "^2.15.8"
boto = {extras = ["crt"], version = "^2.49.0"}
j2lint = "^1.0.0"
stringcase = "^1.2.0"
pytest-django = "^4.5.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
django-debug-toolbar = "^3.5.0"
pytest-drf = "^1.1.2"

[tool.poetry.group.dev.dependencies]
psycopg2-binary = "^2.9.5"
responses = "^0.22.0"
pytest-mock = "^3.10.0"
model-bakery = "^1.9.0"
pytest-socket = "^0.5.1"
pre-commit = "^2.20.0"
faker = "^15.3.4"
pytest = "^7.2.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --disable-socket --no-migrations"
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]

[tool.flake8]
max-line-length = 88
select = "C,E,F,W,B,B950"
extend-ignore = "E203, E501"

[tool.black]
extend_exclude = '^.*\b(migrations)\b.*$'


[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
