version: '3.8'

services:
  app:
    &app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: devcontainer.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  sass:
    <<: *app
    command: python /workspaces/manage.py sass stl_dsa/static/sass stl_dsa/static/css --watch
    # command: ls /workspaces

volumes:
  postgres-data:
